config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :roles
  devise_for :users, :controllers => {omniauth_callbacks: "users/omniauth_callbacks" }

  resources :posts do
    member { post :vote }
    resources :comments do
      member { post :votecomment }
    end
  end

  post '/tinymce_assets' => 'tinymce_assets#create'

  resources :users
  get 'tags/:tag', to: 'posts#index', as: :tag

  root 'posts#index'

end

app/views/shared/_sign_in.html.erb
<div class="modal fade" id="sign_in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign in</h4>
      </div>
      <div class="modal-body">
        <%= form_for(User.new, url: session_path(:user), html:{id: 'sign_in_user'}) do |f| %>
            <div class="field">
              <%= f.label :email %><br />
              <%= f.email_field :email, autofocus: true %>
            </div>

            <div class="field">
              <%= f.label :password %><br />
              <%= f.password_field :password, autocomplete: "off" %>
            </div>

            <div class="field">
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me %>
            </div>

            <div class="actions">
              <%= f.submit "Log in" %>
            </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sign_up.html.erb
<div class="modal fade" id="sign_up" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign up</h4>
      </div>
      <div class="modal-body">
        <%= form_for(User.new, url: registration_path(:user), validate: true, html:{id: 'sign_up_user'}) do |f| %>

      <div class="field">
              <%= f.label :email %><br />
              <%= f.email_field :email, autofocus: true %>
            </div>

            <div><%= f.label :name %><br />
              <%= f.text_field :name, autofocus: true %>
            </div>

            <div class="field">
              <%= f.label :password %>
              <% if @validatable %>
                  <em>(<%= @minimum_password_length %> characters minimum)</em>
              <% end %><br />
              <%= f.password_field :password, autocomplete: "off" %>
            </div>

            <div class="field">
              <%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, autocomplete: "off" %>
            </div>

            <div class="actions">
              <%= f.submit "Sign up" %>
            </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>