config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :roles
  devise_for :users, :controllers => {omniauth_callbacks: "users/omniauth_callbacks" }

  resources :posts do
    member { post :vote }
    resources :comments do
      member { post :votecomment }
    end
  end

  post '/tinymce_assets' => 'tinymce_assets#create'

  resources :users
  get 'tags/:tag', to: 'posts#index', as: :tag

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user

  acts_as_punchable
  extend FriendlyId
  friendly_id :title, use: :slugged
  acts_as_taggable
  acts_as_commentable
  has_reputation :votes, source: :user, aggregated_by: :sum

  scope :active, -> { where status: 'active'}
  scope :deactivate, -> { where status: 'deactivate'}

  validates :tag_list, presence: true
  validates :title, presence: true
  validates :title, length: { minimum: 3 }
  validates :content, presence: true
  validates :content, length: { minimum: 150 }
  validates :tag_list, presence: true


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :vote]
  before_filter :authenticate_user!, only: [ :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /posts
  # GET /posts.json

  def index
    if params[:tag].present?
      @posts = Post.active.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 10)
    else
      @posts = Post.active.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post.punch(request)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.status = "deactivate"

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vote
    value = params[:type] == "up" ? 1 : -1
    @post = Post.friendly.find(params[:id])
    @post.add_or_update_evaluation(:votes, value, current_user)
    respond_to do |format|
      format.html { redirect_to :back, notice: "Thank you for voting" }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :status, :tag_list)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<tr id="comment_<%= comment.id %>">

  <td><%= comment.comment %></td>

  <td><%= comment.user.name %></td>

  <td><%= image_tag comment.user.avatar.url, class: 'img-circle', size: "50x50" %></td>

  <td><%= comment.created_at.strftime("%d.%m.%Y в %H:%M") %></td>

  <% if can? :destroy, @comment %>
      <td><%= link_to 'Destroy', post_comment_path(@post, comment),
                      :confirm => 'Are you sure?',
                      :method => :delete, :remote => true %></td>
  <% end %>

  <td><div id='votecomment_<%= comment.id %>'>
    <%= render "votecomment", :comment => comment%>
  </div></td>

</tr>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
    <div class="field">
      <%= f.label :slug %><br>
      <%= f.text_field :slug %>
    </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= tinymce %>
    <%= f.text_area :content, class: 'tinymce', rows: 40, cols: 120 %>
  </div>
    <% if can? :noaccess, Post %>
    <div class="field">
      <%= f.label :status %><br>
      <%= select :post, :status, [["active", "active"], ["deactivate", "deactivate"]], :selected => "ruby_base" %>
    </div>
    <% end %>
    <div class="field">
      <%= f.label :tag_list, "Tags (separated by commas)" %><br />
      <%= f.text_field :tag_list %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_vote.html.erb
<p>
  <b>Vote:</b>
  <%= pluralize @post.reputation_for(:votes).to_i, "vote" %>
  <%= link_to "up", vote_post_path(@post, type: "up"), method: "post", remote: true %>
  | <%= link_to "down", vote_post_path(@post, type: "down"), method: "post", remote: true %>
</p>

app/views/posts/_votecomment.html.erb
<p>
  <b>Vote:</b>
  <%= pluralize comment.reputation_for(:votes).to_i, "votecomment" %>
  <% if user_signed_in? %>
      <%= link_to "up", votecomment_post_comment_path(@post, comment, type: "up"), method: "post", remote: true %>
      | <%= link_to "down", votecomment_post_comment_path(@post, comment, type: "down"), method: "post", remote: true %>
  <% end %>
</p>

app/views/posts/edit.html.erb
<%- title "#{@post.title}" %>

<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= truncate(post.content, length: 30, escape: false).html_safe %></td>
        <td><%= post.user.name %></td>
        <td><%= post.created_at.strftime '%d.%m.%Y' %></td>
        <td><% post.tags.any? %>
          <% post.tags.each do |tag| %>
    <span class="label label-teal">
        <%= link_to tag.name, tag_path(tag.name) %>
     </span>
          <% end %></td>
        <td><%= post.comments.count %></td>
        <td><%= link_to 'Show', post %></td>

        <% if can? :update, post %>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <% end %>

        <% if can? :destroy, post %>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>

<% if can? :create, Post %>
    <%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%- title "#{@post.title}" %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content.html_safe %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @post.created_at.strftime '%d.%m.%Y' %>
</p>

<p>
  <strong>Hits:</strong>
  <%= @post.hits%>
</p>

<p>
  <strong>Social button:</strong>
  <%= social_share_button_tag(@post.title) %>
</p>

<p>
  <strong>Tags:</strong>
  <% @post.tags.any? %>
  <% @post.tags.each do |tag| %>
    <span class="label label-teal">
        <%= link_to tag.name, tag_path(tag.name) %>
     </span>
  <% end %>
</p>

<div id='vote'>
  <%= render "vote"%>
</div>

<div><h2>Comments</h2> <h2 id='count'>(<%= @post.comments.count %>)</h2> </div>

<table>
  <thead>
  <tr>
    <th>Comment</th>
    <th>name</th>
    <th>avatar</th>
    <th>Time</th>
    <th>5</th>
  </tr>
  </thead>

  <tbody>

  <tbody id='comments'>
  <% @post.comments.each do |comment| %>

      <%= render "comments", :comment => comment %>

  <% end %>
  </tbody>
</table>

<% if can? :create, Comment %>
    <div id="comment_error">
    </div>
    <h2>Add a comment:</h2>
    <%= form_for([@post, @post.comments.build], remote: true) do |f| %>
        <div class="field">
          <%= f.hidden_field :user_id %>
          <%= f.label :comment %><br />
          <%= f.text_area :comment %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
    <% end %>
<% else %>
    <p> In order to post your review, you must <%= link_to 'sign in', new_user_session_path %> or <%= link_to 'sign up', new_user_registration_path %></p>
<% end %>




<% if can? :update, @post %>
    <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>

app/views/posts/vote.js.erb
$('#vote').html('<%= escape_javascript render("vote") %>');